parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    FuzzingBits\Stencil\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    FuzzingBits\Stencil\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    FuzzingBits\Stencil\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
